### ISSUE TITLE
Skimr V2 release checklist

### ISSUE THREAD

**Issue by michaelquinn32** [ropensci/skimr#383]
## Stability/ Code quality
- [x] test on windows
- [x] Prerelease: Remove call to dplyr remote from DESCRIPTION
- [ ] stretch: test on development version of all tidyverse packages
- [x] test coverage (#103)
- [x] stretch: Improve performance (#370)

## API Changes
- [x] check for other rough spots with old API

## Communication
- [x] update NEWS ([style recommendations](https://style.tidyverse.org/news.html))
- [x] update vignettes (possibly #105, but that might stay open after)
- [x] update readme
- [x] communicate to users about release
- [ ] settle on .onAttach message, including recommended printing options. (#376)
- [x] review open issues and update status, solve or close
- [x] stretch: Make packagedown site.

## Other
- [ ]  stretch: Add a pre-commit hook for calling styler on commit. 
- [X] Deal with trailing whitespace in comments (r-lib/styler#464)

**Comment by GegznaV** [comment]
When one can expect **skimr** v2 released on CRAN?

**Comment by michaelquinn32** [comment]
I think we're pretty close. There were a couple of big outstanding bugs that we've just been able to resolve. I don't have much else to work on. @elinw, how about you?

**Comment by elinw** [comment]
I think we need to write a blog post on ropensci ... we've only really communicated via the issue tracker an twitter.  
There is still work to do on the vignettes.  
I'm still testing the two open PRs.  
Then we also need to go though all of the changes to v1 and make sure they are incorporated in v2.

**Comment by elinw** [comment]
I'm thinking this week unless something comes up today, I'm ready to submit.

**Comment by elinw** [comment]
It's submitted ... now it's up to CRAN, but should be soon.
